package ${enum.typePackage};


/*
WARNING: This file was auto-generated by MagicDraw MBRS plug-in. 
Don't update it, because if you run the generator again, your changes will be over overrode!
*/
public enum ${enum.name}{

	<#if values?size != 0>
	<#list values as e>${e} <#if e_has_next>,</#if>
	</#list>;</#if>
}