package ${class.typePackage};

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Date;


<#assign mylist=class.typePackage?split(".")>


<#assign x=mylist?size-2>
<#assign baseDir=mylist[0]>

<#list 1..x as i>
	<#assign baseDir = baseDir+"."+mylist[i]>
</#list>

import ${baseDir}.model.*;
import ${baseDir}.service.*;
import ${baseDir}.mapper.*;
import ${baseDir}.dto.*;
import ${baseDir}.repository.*;

/*
WARNING: This file was auto-generated by MagicDraw MBRS plug-in. 
Don't update it, because if you run the generator again, your changes will be over overrode!
If you want to extend this interface see "BookExtendedServiceImpl.java"
*/

@Service
public class ${class.name}ServiceImpl implements ${class.name}Service{

	@Autowired
	private ${class.name}Repository ${class.name?uncap_first}Repository;
	
	<#list properties as property>
		<#if property.association>
	@Autowired
	private ${property.type.name?cap_first}Repository ${property.type.name?uncap_first}Reposiroty;
	
		</#if>
	</#list>
	@Override
	public ${class.name} findOne(Long id){
		return ${class.name?uncap_first}Repository.findById(id).orElse(null);
	}
	
	@Override
	public List<${class.name}> findAll(){
		return ${class.name?uncap_first}Repository.findAll();
	}
	
	<#list properties as property>
		<#if property.name != "id" && property.upper == 1 && !property.association>
	@Override
	public List<${class.name}> findBy${property.name?cap_first}(${property.type.name} ${property.name}){
		return ${class.name?uncap_first}Repository.findBy${property.name?cap_first}(${property.name});
	}
		</#if>
	</#list>

	<#if class.uiClass?? && ( class.uiClass.create == true || class.uiClass.update)>
	@Override
	public ${class.name} save(${class.name}DTO ${class.name?uncap_first}){
		${class.name} newEntity = new ${class.name}();
		<#list properties as property>
			<#if !property.association>
		newEntity.set${property.name?cap_first}(${class.name?uncap_first}.get${property.name?cap_first}());
			<#else>
				<#if property.upper == 1>
		newEntity.set${property.name?cap_first}(${property.type.name?uncap_first}Reposiroty.findById(${class.name?uncap_first}.get${property.name?cap_first}().getId()).orElse(null));	
				<#else>
		// asocijacija ${property.type.name?uncap_first}Reposiroty		
				</#if>
			</#if>
		</#list>
		
		return ${class.name?uncap_first}Repository.save(newEntity);
	}
	</#if>
	<#if class.uiClass?? && (class.uiClass.update)>
	@Override
	public ${class.name} update(${class.name}DTO ${class.name?uncap_first}) throws Exception{
		${class.name} existing = ${class.name?uncap_first}Repository.findById(${class.name?uncap_first}.getId()).orElse(null);
		if(existing == null){
			throw new Exception("${class.name} doesn't exist");
		}
		//update entity
		<#list properties as property>
			<#if !property.association>
		existing.set${property.name?cap_first}(${class.name?uncap_first}.get${property.name?cap_first}());
			<#else>
				<#if property.upper == 1>
		existing.set${property.name?cap_first}(${property.type.name?uncap_first}Reposiroty.findById(${class.name?uncap_first}.get${property.name?cap_first}().getId()).orElse(null));	
				<#else>
		// asocijacija ${property.type.name?uncap_first}Repository				
				</#if>
			</#if>
		</#list>
		
		return ${class.name?uncap_first}Repository.save(existing);
	}
	</#if>
	<#if class.uiClass?? && ( class.uiClass.delete == true)>
	@Override
	public ${class.name} remove(Long id)  throws Exception{
		${class.name} existing = ${class.name?uncap_first}Repository.findById(id).orElse(null);
		if(existing == null){
			throw new Exception("${class.name} doesn't exist");
		}
		${class.name?uncap_first}Repository.delete(existing);
		
		return existing;
	}
	</#if>
}